# Generated by Django 6.0.5 on 2026-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsnapshot",
            name="liquidity_source",
            field=models.CharField(
                default="unavailable",
                help_text="quote_only, daily_candles, intraday_candles, unavailable",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="liquidity_timeframe",
            field=models.CharField(
                blank=True,
                help_text="Timeframe used to derive liquidity, for example 15m, 1h, 1d.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="marketsnapshot",
            name="liquidity_warning",
            field=models.TextField(blank=True),
        ),
    ]
